JOKES = [
	"What's the difference between a porcupine and a Porsche? -- The porcupine has the pricks on the outside.",
	"Why did the duck go to rehab? Because he was a quack addict!",
	"What's the difference between a smart man and a stupid man? Nothing. They both think they know everything.",
	"If con is the opposite of pro, it must mean Congress is the opposite of progress?",
	"My mom never saw the irony in calling me a son-of-a-bitch.",
	"What did the fish say when he swam into the wall? -- Damn",
	"Why do men get married? So they don't have to hold-in their stomachs any more.",
	"What do you do if a idiot throws a grenade at you? -- Pull the pin and throw it back at him!",
	"What happened when the butcher backed into his meat grinder? -- He got a little behind in his work!",
	"What's the difference between roast beef and pea soup? -- Anyone can roast beef.",
	"I am a nobody, nobody is perfect, therefore I am perfect.",
	"What do you call a sheep with no legs? A cloud."  ,
	"Doctor: You’re overweight. Patient: I think I want a second opinion. Doctor: You're also ugly.",
	"What do you call a bear with no teeth? -- A gummy bear!",
	"If practice makes perfect, and nobody's perfect, why practice?",
	"I pretend to work here, they pretend to pay me.",
	"What did the ocean say to the beach? Nothing, it just waved.",
	"How do you make holy water? You boil the hell out of it.",
	"Irish diplomacy - the art of telling someone to go to hell in such a way they’ll look forward to the trip.",
	"I asked my wife to let me know next time she has an orgasm but she said that she doesn't like to call me at work.",
	"What's the difference between an oral and a rectal thermometer? -- The taste!",
	"Never argue with a fool, they will lower you to their level, and then beat you with experience.",
	"I wondered why the frisbee was getting bigger, and then it hit me.",
	"I used to like my neighbors, until they put a password on their Wi-Fi.",
	"How can you tell when a lawyer is lying? -- His lips are moving.",
	"Have you ever smelled mothballs? How did you get his little legs apart?",
	"What are the three words guaranteed to humiliate men everywhere? 'Hold my purse.'",
	"Two snowmen are standing in a field. One says to the other : 'Funny, I smell carrots too'.",
	"He who laughs last thinks slowest."
]

RAN = [
"hello",
"PING",
"weather Toronto",
"Real Estate",
"I am so blue I'm greener than purple.",
"Llamas eat sexy paper clips",
"Banana error.",
"A hotdog on a bridge",
"My nose is a communist.",
"What do you think about the magical yellow unicorn who dances on the rainbow with a spoonful of blue cheese dressing?",
"A fuzzy snake ate the clouds",
"No sheep is quite as crooked as a bed",
"I stepped on a Corn Flake, now I'm a Cereal Killer",
"Are you a fan of delicious flavor?",
"Call the pineapple if you feel happy",
"Everyday a grape licks a friendly cow",
"Screw world peace, I want a pony"
]